### PR TITLE
made adjustments so there server is overtime

### PR DESCRIPTION
**Pull request by JustinBenedick**
This config just  gives the server overtime rules as its default

### CODE REVIEW

**Comment by dudleycodes** [comment]
@JustinBenedick - rejecting this pull request as it's a request to merge the change into master and not into a new branch.

**Comment by dudleycodes** [comment]
image

**Comment by JustinBenedick** [comment]
Just tried again. I think it needs an empty overtime branch to compare to. 
firefox_2018-11-11_20-58-50

**Comment by JustinBenedick** [comment]
changed base to new overtime

**Pull request closed without merging**
